# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

####Imports, downloads e bibliotecas

#####imports
"""

import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.probability import FreqDist

import re, string

import pandas as pd

"""#####pips"""

!pip install -U spacy
!python -m spacy download pt_core_news_lg

"""###Preprocessamento dos tweets

#####filepaths e variáveis importantes
""""

termo = 'biscate'

"""####load dataset

#####carregando arquivo dividido em duas partes
"""

def open_splited_file(termo):
    path_to_csv = ''

    tweets_1 = pd.read_csv(path_to_csv + termo + '1.csv',
                            parse_dates = ['created_at'])
    tweets_2 = pd.read_csv(path_to_csv + termo + '2.csv',
                            parse_dates = ['created_at'])
    tweets_df = pd.concat([tweets_1,tweets_2], ignore_index=True)

    del tweets_1, tweets_2

    return tweets_df

"""#####carregando arquivo único"""

def open_single_file(termo):
    path_to_csv = ''
    tweets_df = pd.read_csv(path_to_csv + termo + '.csv',
                            parse_dates = ['created_at'])

    return tweets_df

tweets_df = open_single_file(termo)

"""#####descrição das colunas do df"""

# tweets_df.columns

"""#####selecionando colunas relevantes e renomeando"""

def get_columns(tweets_df):
    tweets_df = tweets_df[['created_at',
                        'text',
                        'lang',
                        'author.location',
                        'geo.coordinates.coordinates',
                        'geo.coordinates.type',
                        'geo.country',
                        'geo.country_code'
                        ]]

    return tweets_df

def rename_columns(tweets_df):
    tweets_df.rename(columns={'created_at':'date',
                            'text':'tweet',
                            'lang':'lang',
                            'author.location':'author_location',
                            'geo.coordinates.coordinates':'geo_coordinates',
                            'geo.coordinates.type':'geo_type_coordinates',
                            'geo.country':'geo_location',
                            'geo.country_code':'geo_code'
                            },
                                inplace=True)
    return tweets_df

tweets_df = get_columns(tweets_df)
tweets_df = rename_columns(tweets_df)

# tweets_df.head()

"""#####formatando datas (apenas ano)"""

def format_date(tweets_df):
    tweets_df['date'] = pd.to_datetime(tweets_df['date'], errors='coerce').dt.year
    tweets_df = tweets_df.sort_values(by=['date']).reset_index(drop=True)

    return tweets_df

tweets_df = format_date(tweets_df)


print(tweets_df['tweet'][5410])

"""####preprocessamento

#####função de limpeza de texto
"""


def clean(text):
    text = re.sub(r'\\n', '\n', str(text))
    text = re.sub(r'\n', ' ', str(text))

    # coloca todas as letras em minúsculo
    text = text.lower()
    # substitui os caracteres _ por espaço em branco
    text = re.sub(r'_+', ' ', str(text))
    # remove caracteres especiais e pontuações
    text = re.sub(r'[^\w\s]', '', str(text))
    # substitui as versões acentuadas das vogais pela vogal sem acento
    text = re.sub(r'[àáâãäå]', 'a', str(text))
    text = re.sub(r'[èéêë]', 'e', str(text))
    text = re.sub(r'[ìíîï]', 'i', str(text))
    text = re.sub(r'[òóôõöø]', 'o', str(text))
    text = re.sub(r'[ùúûü]', 'u', str(text))
    # remove 'kk...' ou 'haha...'
    # text = re.sub(r'k{2,}|h{2,}', '', str(text))
    text = re.sub(r'(k{2,})', 'k', str(text)) # sequências de k's em palavras
    text = re.sub(r'(\bk{2,}\b)', '', str(text)) # sequências de k's como palavras
    # text = re.sub(r'h(a|h)*', '', str(text)) # sequências de ha's em palavras
    text = re.sub(r'\bk(a|k)*\b', '', str(text)) # sequências de ka's como palavras
    text = re.sub(r'\bh(a|h)*\b', '', str(text)) # sequências de ha's como palavras
    # remove urls
    text = re.sub(r'http\S+', '', str(text))
    # remove menções a usuários
    text = re.sub(r'@\w+', '', str(text))
    # remove hashtags
    text = re.sub(r'#\w+', '', str(text))
    # remove números
    text = re.sub(r'\d+', '', str(text))
    # remove emojis
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', str(text))
    # remove espaços em branco extras
    text = re.sub(r'\s+', ' ', str(text))


    text = [w for w in word_tokenize(text) if (w not in stopwords and len(w)>2)]


    return text

def clean_glove(text):
    text = re.sub(r'\\n', '\n', str(text))
    text = re.sub(r'\n', ' ', str(text))

    # coloca todas as letras em minúsculo
    text = text.lower()
    # substitui os caracteres _ por espaço em branco
    text = re.sub(r'_+', ' ', str(text))
    # remove caracteres especiais e pontuações
    text = re.sub(r'[^\w\s]', '', str(text))
    # substitui as versões acentuadas das vogais pela vogal sem acento
    text = re.sub(r'[àáâãäå]', 'a', str(text))
    text = re.sub(r'[èéêë]', 'e', str(text))
    text = re.sub(r'[ìíîï]', 'i', str(text))
    text = re.sub(r'[òóôõöø]', 'o', str(text))
    text = re.sub(r'[ùúûü]', 'u', str(text))
    # remove 'kk...' ou 'haha...'
    # text = re.sub(r'k{2,}|h{2,}', '', str(text))
    text = re.sub(r'(k{2,})', 'k', str(text)) # sequências de k's em palavras
    text = re.sub(r'(\bk{2,}\b)', '', str(text)) # sequências de k's como palavras
    # text = re.sub(r'h(a|h)*', '', str(text)) # sequências de ha's em palavras
    text = re.sub(r'\bk(a|k)*\b', '', str(text)) # sequências de ka's como palavras
    text = re.sub(r'\bh(a|h)*\b', '', str(text)) # sequências de ha's como palavras
    # remove urls
    text = re.sub(r'http\S+', '', str(text))
    # remove menções a usuários
    text = re.sub(r'@\w+', '', str(text))
    # remove hashtags
    text = re.sub(r'#\w+', '', str(text))
    # remove números
    text = re.sub(r'\d+', '', str(text))
    # remove emojis
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', str(text))
    # remove espaços em branco extras
    text = re.sub(r'\s+', ' ', str(text))

    text = [w for w in word_tokenize(text) if (w not in stop_words and len(w)>2)]


    return text


"""#####substituir termo por token de época"""

def alter_word(df, old_word):
    df.loc[df['date'] <= 2017, 'tweet'] = [
        [old_word.upper()+'20132017' if word == old_word else word for word in words]
        for words in df.loc[df['date'] <= 2017, 'tweet']
    ]
    df.loc[df['date'] > 2017, 'tweet'] = [
        [old_word.upper()+'20182022' if word == old_word else word for word in words]
        for words in df.loc[df['date'] > 2017, 'tweet']
    ]
    return df

"""####salvando arquivos tratados"""

def save_column_as_csv(df, column_name, termo):
    file_path =  '' + termo + '_prepro.csv'
    df[[column_name]].to_csv(file_path, index=False, encoding="utf-8")

def save_dataframe_as_csv(df, termo):
    file_path =  '' + termo + '_all__prepro.csv'
    df.to_csv(file_path, index=False, encoding="utf-8")


"""####salvando arquivos (append)
criado para o processamento de 'mortal' por ser um arquivo muito grande
"""

def append_column_as_csv(df, column_name, termo):
    file_path =  '' + termo + '_prepro.csv'
    df[[column_name]].to_csv(file_path, mode='a', index=False, header=False, encoding='utf-8')

def append_dataframe_as_csv(df, termo):
    file_path =  '' + termo + '_all__prepro.csv'
    df.to_csv(file_path, mode='a', index=False, header=False, encoding='utf-8')

"""#Execute all"""

stopwords = nltk.corpus.stopwords.words('portuguese')

att_stopwords = ['tal', 'tão']
stopwords = stopwords + att_stopwords

termos_1 = ['biscate',
            'prima',
            'goleiro'
           ]

for termo in termos_1:
    tweets_df = open_single_file(termo)
    tweets_df = get_columns(tweets_df)
    tweets_df = rename_columns(tweets_df)
    tweets_df = format_date(tweets_df)
    tweets_df['tweet'] = tweets_df['tweet'].apply(clean)
    tweets_df = alter_word(tweets_df, termo)

    save_column_as_csv(tweets_df, 'tweet', termo)
    save_dataframe_as_csv(tweets_df, termo)
    del tweets_df

termos_2 = ['birosca',
            'carambola',
            'estilete',
            'peteca',
            'ruge',
            'lagarta',
            'broca',
            'perereca'
           ]

for termo in termos_2:
    tweets_df = open_splited_file(termo)
    tweets_df = get_columns(tweets_df)
    tweets_df = rename_columns(tweets_df)
    tweets_df = format_date(tweets_df)
    tweets_df['tweet'] = tweets_df['tweet'].apply(clean)
    tweets_df = alter_word(tweets_df, termo)

    save_column_as_csv(tweets_df, 'tweet', termo)
    save_dataframe_as_csv(tweets_df, termo)
    del tweets_df

termo = 'mortal'

path_to_csv = ''

tweets_df = pd.read_csv(path_to_csv + termo + '1.csv',
                        parse_dates = ['created_at'])
tweets_df = get_columns(tweets_df)
tweets_df = rename_columns(tweets_df)
tweets_df = format_date(tweets_df)
tweets_df['tweet'] = tweets_df['tweet'].apply(clean)
tweets_df = alter_word(tweets_df, termo)

save_column_as_csv(tweets_df, 'tweet', termo)
save_dataframe_as_csv(tweets_df, termo)
del tweets_df

tweets_df = pd.read_csv(path_to_csv + termo + '2.csv',
                        parse_dates = ['created_at'])
tweets_df = get_columns(tweets_df)
tweets_df = rename_columns(tweets_df)
tweets_df = format_date(tweets_df)
tweets_df['tweet'] = tweets_df['tweet'].apply(clean)
tweets_df = alter_word(tweets_df, termo)

append_column_as_csv(tweets_df, 'tweet', termo)
append_dataframe_as_csv(tweets_df, termo)
del tweets_df
